In [1]:
import pandas as pd
import datetime
import mpl_finance
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
from mpl_finance import candlestick_ohlc
from IPython import get_ipython
import numpy as np
import matplotlib.ticker as mticker

In [2]:
USD_JPY_df =  pd.read_pickle("C:/Users/pebaqu/OneDrive - SAS/Profiles for l10c581/l10c581/Desktop/Personal/Python/Datasets/2018-07-01_USD_JPY")

In [3]:
display(USD_JPY_df)
print(USD_JPY_df.columns)

,Complete,Volume,Time,Bid_Open,Bid_High,Bid_Low,Bid_Close,Ask_Open,Ask_High,Ask_Low,Ask_Close
Time,,,,,,,,,,,
2018-07-01 21:00:00,b'True',1,2018-07-01 21:00:00,110.635,110.635,110.635,110.635,110.715,110.715,110.715,110.715
2018-07-01 21:00:15,b'True',1,2018-07-01 21:00:15,110.584,110.584,110.584,110.584,110.664,110.664,110.664,110.664
2018-07-01 21:00:50,b'True',1,2018-07-01 21:00:50,110.592,110.592,110.592,110.592,110.672,110.672,110.672,110.672
2018-07-01 21:00:55,b'True',4,2018-07-01 21:00:55,110.588,110.661,110.588,110.661,110.668,110.741,110.668,110.741
2018-07-01 21:01:00,b'True',1,2018-07-01 21:01:00,110.665,110.665,110.665,110.665,110.745,110.745,110.745,110.745
2018-07-01 21:01:05,b'True',5,2018-07-01 21:01:05,110.660,110.660,110.596,110.596,110.740,110.740,110.676,110.676
2018-07-01 21:01:10,b'True',1,2018-07-01 21:01:10,110.600,110.600,110.600,110.600,110.680,110.680,110.680,110.680
2018-07-01 21:01:30,b'True',1,2018-07-01 21:01:30,110.604,110.604,110.604,110.604,110.684,110.684,110.684,110.684
2018-07-01 21:01:45,b'True',3,2018-07-01 21:01:45,110.612,110.622,110.612,110.622,110.692,110.702,110.692,110.702
2018-07-01 21:02:00,b'True',2,2018-07-01 21:02:00,110.622,110.622,110.622,110.622,110.702,110.702,110.702,110.702
2018-07-01 21:02:05,b'True',1,2018-07-01 21:02:05,110.628,110.628,110.628,110.628,110.708,110.708,110.708,110.708
2018-07-01 21:02:10,b'True',5,2018-07-01 21:02:10,110.624,110.624,110.602,110.602,110.702,110.702,110.682,110.682
2018-07-01 21:02:35,b'True',1,2018-07-01 21:02:35,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686
2018-07-01 21:02:40,b'True',1,2018-07-01 21:02:40,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690
2018-07-01 21:02:45,b'True',1,2018-07-01 21:02:45,110.615,110.615,110.615,110.615,110.695,110.695,110.695,110.695
2018-07-01 21:03:05,b'True',1,2018-07-01 21:03:05,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690
2018-07-01 21:03:25,b'True',1,2018-07-01 21:03:25,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686
2018-07-01 21:04:20,b'True',1,2018-07-01 21:04:20,110.601,110.601,110.601,110.601,110.681,110.681,110.681,110.681
2018-07-01 21:04:40,b'True',1,2018-07-01 21:04:40,110.595,110.595,110.595,110.595,110.675,110.675,110.675,110.675
2018-07-01 21:04:45,b'True',4,2018-07-01 21:04:45,110.588,110.592,110.582,110.582,110.668,110.672,110.662,110.662
2018-07-01 21:04:55,b'True',1,2018-07-01 21:04:55,110.590,110.590,110.590,110.590,110.667,110.667,110.667,110.667
2018-07-01 21:05:00,b'True',2,2018-07-01 21:05:00,110.593,110.600,110.593,110.600,110.673,110.680,110.673,110.680
2018-07-01 21:05:20,b'True',30,2018-07-01 21:05:20,110.592,110.600,110.581,110.589,110.672,110.680,110.661,110.669
2018-07-01 21:05:25,b'True',22,2018-07-01 21:05:25,110.596,110.597,110.581,110.588,110.676,110.677,110.661,110.668
2018-07-01 21:05:30,b'True',6,2018-07-01 21:05:30,110.595,110.599,110.590,110.599,110.675,110.679,110.670,110.679
2018-07-01 21:06:10,b'True',3,2018-07-01 21:06:10,110.595,110.595,110.582,110.582,110.675,110.675,110.662,110.662
2018-07-01 21:06:15,b'True',1,2018-07-01 21:06:15,110.594,110.594,110.594,110.594,110.658,110.658,110.658,110.658
2018-07-01 21:07:10,b'True',1,2018-07-01 21:07:10,110.596,110.596,110.596,110.596,110.665,110.665,110.665,110.665
2018-07-01 21:08:05,b'True',2,2018-07-01 21:08:05,110.603,110.610,110.603,110.610,110.668,110.669,110.668,110.669
2018-07-01 21:08:10,b'True',1,2018-07-01 21:08:10,110.613,110.613,110.613,110.613,110.675,110.675,110.675,110.675
...,...,...,...,...,...,...,...,...,...,...,...
2018-07-31 23:56:45,b'True',3,2018-07-31 23:56:45,111.774,111.778,111.774,111.778,111.788,111.793,111.788,111.793
2018-07-31 23:57:00,b'True',4,2018-07-31 23:57:00,111.776,111.778,111.774,111.774,111.791,111.793,111.788,111.788
2018-07-31 23:57:05,b'True',5,2018-07-31 23:57:05,111.776,111.786,111.776,111.786,111.791,111.800,111.791,111.800
2018-07-31 23:57:10,b'True',2,2018-07-31 23:57:10,111.788,111.790,111.788,111.790,111.803,111.805,111.803,111.805
2018-07-31 23:57:15,b'True',4,2018-07-31 23:57:15,111.788,111.788,111.781,111.781,111.803,111.803,111.796,111.796
2018-07-31 23:57:20,b'True',2,2018-07-31 23:57:20,111.784,111.784,111.781,111.781,111.797,111.797,111.796,111.796
2018-07-31 23:57:25,b'True',3,2018-07-31 23:57:25,111.784,111.788,111.784,111.788,111.797,111.803,111.797,111.803
2018-07-31 23:57:35,b'True',4,2018-07-31 23:57:35,111.790,111.790,111.786,111.789,111.805,111.805,111.801,111.803
2018-07-31 23:57:40,b'True',2,2018-07-31 23:57:40,111.791,111.794,111.791,111.794,111.806,111.807,111.806,111.807
2018-07-31 23:57:45,b'True',3,2018-07-31 23:57:45,111.796,111.796,111.791,111.791,111.810,111.810,111.805,111.805
2018-07-31 23:57:50,b'True',2,2018-07-31 23:57:50,111.793,111.793,111.791,111.791,111.807,111.807,111.805,111.805
2018-07-31 23:57:55,b'True',1,2018-07-31 23:57:55,111.792,111.792,111.792,111.792,111.808,111.808,111.808,111.808
2018-07-31 23:58:00,b'True',1,2018-07-31 23:58:00,111.796,111.796,111.796,111.796,111.809,111.809,111.809,111.809
2018-07-31 23:58:20,b'True',5,2018-07-31 23:58:20,111.798,111.808,111.798,111.808,111.812,111.821,111.812,111.821
2018-07-31 23:58:25,b'True',7,2018-07-31 23:58:25,111.810,111.815,111.806,111.806,111.824,111.829,111.820,111.820
2018-07-31 23:58:30,b'True',1,2018-07-31 23:58:30,111.803,111.803,111.803,111.803,111.818,111.818,111.818,111.818
2018-07-31 23:58:35,b'True',1,2018-07-31 23:58:35,111.800,111.800,111.800,111.800,111.815,111.815,111.815,111.815
2018-07-31 23:58:40,b'True',1,2018-07-31 23:58:40,111.803,111.803,111.803,111.803,111.817,111.817,111.817,111.817
2018-07-31 23:58:45,b'True',1,2018-07-31 23:58:45,111.805,111.805,111.805,111.805,111.819,111.819,111.819,111.819
2018-07-31 23:58:50,b'True',5,2018-07-31 23:58:50,111.803,111.803,111.800,111.803,111.817,111.818,111.814,111.818
2018-07-31 23:58:55,b'True',1,2018-07-31 23:58:55,111.806,111.806,111.806,111.806,111.819,111.819,111.819,111.819
2018-07-31 23:59:00,b'True',2,2018-07-31 23:59:00,111.807,111.809,111.807,111.809,111.822,111.825,111.822,111.825
2018-07-31 23:59:05,b'True',3,2018-07-31 23:59:05,111.812,111.817,111.812,111.817,111.827,111.832,111.827,111.832
2018-07-31 23:59:10,b'True',4,2018-07-31 23:59:10,111.819,111.819,111.817,111.817,111.834,111.834,111.831,111.831
2018-07-31 23:59:30,b'True',1,2018-07-31 23:59:30,111.814,111.814,111.814,111.814,111.828,111.828,111.828,111.828
2018-07-31 23:59:40,b'True',6,2018-07-31 23:59:40,111.812,111.818,111.808,111.818,111.826,111.833,111.824,111.833
2018-07-31 23:59:45,b'True',2,2018-07-31 23:59:45,111.821,111.821,111.819,111.819,111.835,111.835,111.832,111.832
2018-07-31 23:59:50,b'True',4,2018-07-31 23:59:50,111.821,111.828,111.821,111.828,111.835,111.842,111.835,111.842
2018-07-31 23:59:55,b'True',4,2018-07-31 23:59:55,111.826,111.828,111.826,111.828,111.839,111.843,111.839,111.843
2018-08-01 00:00:00,b'True',16,2018-08-01 00:00:00,111.826,111.826,111.794,111.799,111.841,111.841,111.809,111.814

Index(['Complete', 'Volume', 'Time', 'Bid_Open', 'Bid_High', 'Bid_Low',
       'Bid_Close', 'Ask_Open', 'Ask_High', 'Ask_Low', 'Ask_Close'],
      dtype='object')

In [12]:
USD_JPY_df[USD_JPY_df['Bid_Open']>USD_JPY_df['Bid_Close']]

,Complete,Volume,Time,Bid_Open,Bid_High,Bid_Low,Bid_Close,Ask_Open,Ask_High,Ask_Low,Ask_Close
Time,,,,,,,,,,,
2018-07-01 21:01:05,b'True',5,2018-07-01 21:01:05,110.660,110.660,110.596,110.596,110.740,110.740,110.676,110.676
2018-07-01 21:02:10,b'True',5,2018-07-01 21:02:10,110.624,110.624,110.602,110.602,110.702,110.702,110.682,110.682
2018-07-01 21:04:45,b'True',4,2018-07-01 21:04:45,110.588,110.592,110.582,110.582,110.668,110.672,110.662,110.662
2018-07-01 21:05:20,b'True',30,2018-07-01 21:05:20,110.592,110.600,110.581,110.589,110.672,110.680,110.661,110.669
2018-07-01 21:05:25,b'True',22,2018-07-01 21:05:25,110.596,110.597,110.581,110.588,110.676,110.677,110.661,110.668
2018-07-01 21:06:10,b'True',3,2018-07-01 21:06:10,110.595,110.595,110.582,110.582,110.675,110.675,110.662,110.662
2018-07-01 21:09:25,b'True',4,2018-07-01 21:09:25,110.613,110.614,110.603,110.603,110.675,110.675,110.655,110.655
2018-07-01 21:09:40,b'True',17,2018-07-01 21:09:40,110.644,110.646,110.629,110.632,110.701,110.726,110.700,110.700
2018-07-01 21:10:00,b'True',3,2018-07-01 21:10:00,110.628,110.628,110.622,110.624,110.677,110.682,110.675,110.682
2018-07-01 21:12:15,b'True',14,2018-07-01 21:12:15,110.622,110.626,110.601,110.601,110.679,110.692,110.670,110.676
2018-07-01 21:12:40,b'True',4,2018-07-01 21:12:40,110.639,110.645,110.638,110.638,110.693,110.695,110.688,110.688
2018-07-01 21:13:25,b'True',5,2018-07-01 21:13:25,110.624,110.624,110.594,110.596,110.686,110.686,110.662,110.662
2018-07-01 21:14:05,b'True',3,2018-07-01 21:14:05,110.606,110.606,110.602,110.602,110.649,110.649,110.640,110.640
2018-07-01 21:15:50,b'True',3,2018-07-01 21:15:50,110.601,110.601,110.597,110.598,110.673,110.673,110.657,110.657
2018-07-01 21:15:55,b'True',4,2018-07-01 21:15:55,110.597,110.597,110.584,110.592,110.645,110.645,110.626,110.626
2018-07-01 21:16:00,b'True',3,2018-07-01 21:16:00,110.598,110.598,110.590,110.594,110.626,110.647,110.626,110.647
2018-07-01 21:16:30,b'True',9,2018-07-01 21:16:30,110.608,110.622,110.588,110.595,110.647,110.681,110.647,110.661
2018-07-01 21:18:05,b'True',2,2018-07-01 21:18:05,110.621,110.621,110.620,110.620,110.654,110.654,110.650,110.650
2018-07-01 21:18:25,b'True',2,2018-07-01 21:18:25,110.650,110.650,110.634,110.634,110.685,110.709,110.685,110.709
2018-07-01 21:18:45,b'True',3,2018-07-01 21:18:45,110.702,110.702,110.681,110.681,110.738,110.741,110.736,110.736
2018-07-01 21:19:05,b'True',2,2018-07-01 21:19:05,110.683,110.683,110.679,110.679,110.751,110.751,110.747,110.747
2018-07-01 21:19:30,b'True',8,2018-07-01 21:19:30,110.675,110.675,110.663,110.670,110.751,110.756,110.746,110.750
2018-07-01 21:19:45,b'True',11,2018-07-01 21:19:45,110.688,110.688,110.646,110.660,110.755,110.758,110.742,110.758
2018-07-01 21:19:55,b'True',2,2018-07-01 21:19:55,110.689,110.689,110.686,110.686,110.753,110.753,110.747,110.747
2018-07-01 21:20:40,b'True',2,2018-07-01 21:20:40,110.688,110.688,110.678,110.678,110.754,110.756,110.754,110.756
2018-07-01 21:20:45,b'True',8,2018-07-01 21:20:45,110.678,110.690,110.673,110.673,110.748,110.772,110.748,110.753
2018-07-01 21:20:55,b'True',5,2018-07-01 21:20:55,110.653,110.653,110.625,110.625,110.751,110.751,110.722,110.722
2018-07-01 21:21:15,b'True',3,2018-07-01 21:21:15,110.646,110.646,110.639,110.639,110.711,110.711,110.701,110.701
2018-07-01 21:24:20,b'True',16,2018-07-01 21:24:20,110.771,110.771,110.729,110.735,110.843,110.859,110.832,110.837
2018-07-01 21:25:05,b'True',2,2018-07-01 21:25:05,110.792,110.792,110.791,110.791,110.881,110.881,110.874,110.874
...,...,...,...,...,...,...,...,...,...,...,...
2018-07-31 23:47:45,b'True',2,2018-07-31 23:47:45,111.749,111.749,111.747,111.747,111.763,111.763,111.761,111.761
2018-07-31 23:48:00,b'True',4,2018-07-31 23:48:00,111.751,111.754,111.749,111.749,111.766,111.767,111.763,111.763
2018-07-31 23:48:20,b'True',5,2018-07-31 23:48:20,111.752,111.753,111.746,111.746,111.765,111.768,111.760,111.760
2018-07-31 23:50:10,b'True',4,2018-07-31 23:50:10,111.780,111.780,111.773,111.773,111.795,111.795,111.788,111.788
2018-07-31 23:50:25,b'True',2,2018-07-31 23:50:25,111.782,111.782,111.779,111.779,111.795,111.795,111.793,111.793
2018-07-31 23:50:50,b'True',2,2018-07-31 23:50:50,111.781,111.781,111.779,111.779,111.795,111.795,111.792,111.792
2018-07-31 23:51:00,b'True',4,2018-07-31 23:51:00,111.780,111.781,111.779,111.779,111.796,111.796,111.792,111.793
2018-07-31 23:51:50,b'True',3,2018-07-31 23:51:50,111.782,111.782,111.777,111.777,111.796,111.796,111.791,111.791
2018-07-31 23:52:00,b'True',3,2018-07-31 23:52:00,111.780,111.782,111.779,111.779,111.793,111.796,111.793,111.794
2018-07-31 23:52:20,b'True',3,2018-07-31 23:52:20,111.781,111.781,111.777,111.777,111.795,111.795,111.791,111.791
2018-07-31 23:52:35,b'True',2,2018-07-31 23:52:35,111.774,111.774,111.771,111.771,111.788,111.788,111.787,111.787
2018-07-31 23:52:55,b'True',4,2018-07-31 23:52:55,111.770,111.770,111.765,111.767,111.783,111.783,111.779,111.781
2018-07-31 23:53:05,b'True',2,2018-07-31 23:53:05,111.762,111.762,111.760,111.760,111.777,111.777,111.774,111.774
2018-07-31 23:54:20,b'True',2,2018-07-31 23:54:20,111.787,111.787,111.785,111.785,111.801,111.801,111.799,111.799
2018-07-31 23:54:50,b'True',6,2018-07-31 23:54:50,111.780,111.780,111.772,111.772,111.792,111.792,111.786,111.786
2018-07-31 23:54:55,b'True',2,2018-07-31 23:54:55,111.774,111.774,111.772,111.772,111.788,111.788,111.786,111.786
2018-07-31 23:55:00,b'True',2,2018-07-31 23:55:00,111.774,111.774,111.772,111.772,111.788,111.788,111.785,111.785
2018-07-31 23:55:30,b'True',2,2018-07-31 23:55:30,111.777,111.777,111.774,111.774,111.791,111.791,111.789,111.789
2018-07-31 23:55:40,b'True',2,2018-07-31 23:55:40,111.769,111.769,111.767,111.767,111.783,111.783,111.781,111.781
2018-07-31 23:56:05,b'True',4,2018-07-31 23:56:05,111.774,111.774,111.772,111.772,111.788,111.788,111.786,111.786
2018-07-31 23:57:00,b'True',4,2018-07-31 23:57:00,111.776,111.778,111.774,111.774,111.791,111.793,111.788,111.788
2018-07-31 23:57:15,b'True',4,2018-07-31 23:57:15,111.788,111.788,111.781,111.781,111.803,111.803,111.796,111.796
2018-07-31 23:57:20,b'True',2,2018-07-31 23:57:20,111.784,111.784,111.781,111.781,111.797,111.797,111.796,111.796
2018-07-31 23:57:35,b'True',4,2018-07-31 23:57:35,111.790,111.790,111.786,111.789,111.805,111.805,111.801,111.803
2018-07-31 23:57:45,b'True',3,2018-07-31 23:57:45,111.796,111.796,111.791,111.791,111.810,111.810,111.805,111.805
2018-07-31 23:57:50,b'True',2,2018-07-31 23:57:50,111.793,111.793,111.791,111.791,111.807,111.807,111.805,111.805
2018-07-31 23:58:25,b'True',7,2018-07-31 23:58:25,111.810,111.815,111.806,111.806,111.824,111.829,111.820,111.820
2018-07-31 23:59:10,b'True',4,2018-07-31 23:59:10,111.819,111.819,111.817,111.817,111.834,111.834,111.831,111.831
2018-07-31 23:59:45,b'True',2,2018-07-31 23:59:45,111.821,111.821,111.819,111.819,111.835,111.835,111.832,111.832
2018-08-01 00:00:00,b'True',16,2018-08-01 00:00:00,111.826,111.826,111.794,111.799,111.841,111.841,111.809,111.814

In [17]:
pd.options.mode.chained_assignment = None

df_plot_col = USD_JPY_df.drop(['Complete','Time', 'Volume'], axis=1).copy()
df_plot_sub = df_plot_col[:100]
df_plot_sub['BidAvg']= df_plot_sub[['Bid_Open','Bid_High','Bid_Low','Bid_Close']].mean(axis=1)
df_plot_sub['AskAvg']= df_plot_sub[['Ask_Open','Ask_High','Ask_Low','Ask_Close']].mean(axis=1)

sma = [5,10,20,30,40,50]
lma = [10,20,50,100,250,500]

for x in sma:
    df_plot_sub['Bid_SSMA'+str(x)]= df_plot_sub['Bid_Close'].rolling(x).mean()
    df_plot_sub['Bid_SEMA'+str(x)]= pd.Series.ewm(df_plot_sub['Bid_Close'],span = x).mean()
    
for x in lma:
    df_plot_sub['Bid_LSMA'+str(x)]= df_plot_sub['Bid_Close'].rolling(x).mean()
    df_plot_sub['Bid_LEMA'+str(x)]= pd.Series.ewm(df_plot_sub['Bid_Close'],span = x).mean()

'''
df_plot_sub['Bid_SMA5']= df_plot_sub['Bid_Close'].rolling(5).mean()
df_plot_sub['Bid_EMA5']= pd.Series.ewm(df_plot_sub['Bid_Close'],span = 5).mean()
df_plot_sub['Bid_SMA10']= df_plot_sub['Bid_Close'].rolling(10).mean()
df_plot_sub['Bid_EMA10']= pd.Series.ewm(df_plot_sub['Bid_Close'],span = 10).mean()
'''

display(df_plot_sub)
print(df_plot_sub.columns)

,Bid_Open,Bid_High,Bid_Low,Bid_Close,Ask_Open,Ask_High,Ask_Low,Ask_Close,BidAvg,AskAvg,...,Bid_LSMA20,Bid_LEMA20,Bid_LSMA50,Bid_LEMA50,Bid_LSMA100,Bid_LEMA100,Bid_LSMA250,Bid_LEMA250,Bid_LSMA500,Bid_LEMA500
Time,,,,,,,,,,,,,,,,,,,,,
2018-07-01 21:00:00,110.635,110.635,110.635,110.635,110.715,110.715,110.715,110.715,110.63500,110.71500,...,NaN,110.635000,NaN,110.635000,NaN,110.635000,NaN,110.635000,NaN,110.635000
2018-07-01 21:00:15,110.584,110.584,110.584,110.584,110.664,110.664,110.664,110.664,110.58400,110.66400,...,NaN,110.608225,NaN,110.608990,NaN,110.609245,NaN,110.609398,NaN,110.609449
2018-07-01 21:00:50,110.592,110.592,110.592,110.592,110.672,110.672,110.672,110.672,110.59200,110.67200,...,NaN,110.602267,NaN,110.603099,NaN,110.603381,NaN,110.603552,NaN,110.603609
2018-07-01 21:00:55,110.588,110.661,110.588,110.661,110.668,110.741,110.668,110.741,110.62450,110.70450,...,NaN,110.619223,NaN,110.618454,NaN,110.618221,NaN,110.618087,NaN,110.618043
2018-07-01 21:01:00,110.665,110.665,110.665,110.665,110.745,110.745,110.745,110.745,110.66500,110.74500,...,NaN,110.630296,NaN,110.628522,NaN,110.627955,NaN,110.627620,NaN,110.627510
2018-07-01 21:01:05,110.660,110.660,110.596,110.596,110.740,110.740,110.676,110.676,110.62800,110.70800,...,NaN,110.623061,NaN,110.622546,NaN,110.622359,NaN,110.622244,NaN,110.622206
2018-07-01 21:01:10,110.600,110.600,110.600,110.600,110.680,110.680,110.680,110.680,110.60000,110.68000,...,NaN,110.618701,NaN,110.618926,NaN,110.618970,NaN,110.618990,NaN,110.618995
2018-07-01 21:01:30,110.604,110.604,110.604,110.604,110.684,110.684,110.684,110.684,110.60400,110.68400,...,NaN,110.616160,NaN,110.616789,NaN,110.616965,NaN,110.617063,NaN,110.617094
2018-07-01 21:01:45,110.612,110.622,110.612,110.622,110.692,110.702,110.692,110.702,110.61700,110.69700,...,NaN,110.617096,NaN,110.617465,NaN,110.617571,NaN,110.617629,NaN,110.617648
2018-07-01 21:02:00,110.622,110.622,110.622,110.622,110.702,110.702,110.702,110.702,110.62200,110.70200,...,NaN,110.617835,NaN,110.618004,NaN,110.618054,NaN,110.618082,NaN,110.618091
2018-07-01 21:02:05,110.628,110.628,110.628,110.628,110.708,110.708,110.708,110.708,110.62800,110.70800,...,NaN,110.619285,NaN,110.619105,NaN,110.619052,NaN,110.619020,NaN,110.619010
2018-07-01 21:02:10,110.624,110.624,110.602,110.602,110.702,110.702,110.682,110.682,110.61300,110.69200,...,NaN,110.616931,NaN,110.617346,NaN,110.617469,NaN,110.617539,NaN,110.617561
2018-07-01 21:02:35,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686,110.60600,110.68600,...,NaN,110.615500,NaN,110.616249,NaN,110.616477,NaN,110.616608,NaN,110.616650
2018-07-01 21:02:40,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690,110.61000,110.69000,...,NaN,110.614805,NaN,110.615677,NaN,110.615952,NaN,110.616111,NaN,110.616163
2018-07-01 21:02:45,110.615,110.615,110.615,110.615,110.695,110.695,110.695,110.695,110.61500,110.69500,...,NaN,110.614829,NaN,110.615618,NaN,110.615879,NaN,110.616033,NaN,110.616083
2018-07-01 21:03:05,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690,110.61000,110.69000,...,NaN,110.614253,NaN,110.615152,NaN,110.615454,NaN,110.615633,NaN,110.615692
2018-07-01 21:03:25,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686,110.60600,110.68600,...,NaN,110.613292,NaN,110.614425,NaN,110.614805,NaN,110.615029,NaN,110.615103
2018-07-01 21:04:20,110.601,110.601,110.601,110.601,110.681,110.681,110.681,110.681,110.60100,110.68100,...,NaN,110.611890,NaN,110.613399,NaN,110.613901,NaN,110.614196,NaN,110.614293
2018-07-01 21:04:40,110.595,110.595,110.595,110.595,110.675,110.675,110.675,110.675,110.59500,110.67500,...,NaN,110.609999,NaN,110.612044,NaN,110.612717,NaN,110.613111,NaN,110.613240
2018-07-01 21:04:45,110.588,110.592,110.582,110.582,110.668,110.672,110.662,110.662,110.58600,110.66600,...,110.61180,110.606916,NaN,110.609905,NaN,110.610872,NaN,110.611434,NaN,110.611618
2018-07-01 21:04:55,110.590,110.590,110.590,110.590,110.667,110.667,110.667,110.667,110.59000,110.66700,...,110.60955,110.605080,NaN,110.608531,NaN,110.609667,NaN,110.610330,NaN,110.610547
2018-07-01 21:05:00,110.593,110.600,110.593,110.600,110.673,110.680,110.673,110.680,110.59650,110.67650,...,110.61035,110.604536,NaN,110.607959,NaN,110.609129,NaN,110.609820,NaN,110.610047
2018-07-01 21:05:20,110.592,110.600,110.581,110.589,110.672,110.680,110.661,110.669,110.59050,110.67050,...,110.61020,110.602892,NaN,110.606723,NaN,110.608048,NaN,110.608833,NaN,110.609091
2018-07-01 21:05:25,110.596,110.597,110.581,110.588,110.676,110.677,110.661,110.668,110.59050,110.67050,...,110.60655,110.601333,NaN,110.605534,NaN,110.607007,NaN,110.607883,NaN,110.608171
2018-07-01 21:05:30,110.595,110.599,110.590,110.599,110.675,110.679,110.670,110.679,110.59575,110.67575,...,110.60325,110.601091,NaN,110.605128,NaN,110.606604,NaN,110.607492,NaN,110.607787
2018-07-01 21:06:10,110.595,110.595,110.582,110.582,110.675,110.675,110.662,110.662,110.58850,110.66850,...,110.60255,110.599127,NaN,110.603726,NaN,110.605402,NaN,110.606410,NaN,110.606745
2018-07-01 21:06:15,110.594,110.594,110.594,110.594,110.658,110.658,110.658,110.658,110.59400,110.65800,...,110.60225,110.598604,NaN,110.603148,NaN,110.604861,NaN,110.605901,NaN,110.606248
2018-07-01 21:07:10,110.596,110.596,110.596,110.596,110.665,110.665,110.665,110.665,110.59600,110.66500,...,110.60185,110.598340,NaN,110.602732,NaN,110.604452,NaN,110.605508,NaN,110.605861
2018-07-01 21:08:05,110.603,110.610,110.603,110.610,110.668,110.669,110.668,110.669,110.60650,110.66850,...,110.60125,110.599515,NaN,110.603147,NaN,110.604701,NaN,110.605681,NaN,110.606012
2018-07-01 21:08:10,110.613,110.613,110.613,110.613,110.675,110.675,110.675,110.675,110.61300,110.67500,...,110.60080,110.600866,NaN,110.603700,NaN,110.605066,NaN,110.605954,NaN,110.606259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-01 21:18:30,110.644,110.644,110.644,110.644,110.710,110.710,110.710,110.710,110.64400,110.71000,...,110.61275,110.619438,110.61326,110.614959,NaN,110.613604,NaN,110.612907,NaN,110.612705
2018-07-01 21:18:35,110.641,110.671,110.641,110.671,110.723,110.763,110.723,110.763,110.65600,110.74300,...,110.61620,110.624352,110.61468,110.617287,NaN,110.615094,NaN,110.613964,NaN,110.613635
2018-07-01 21:18:45,110.702,110.702,110.681,110.681,110.738,110.741,110.736,110.736,110.69150,110.73775,...,110.62005,110.629751,110.61652,110.619928,NaN,110.616794,NaN,110.615172,NaN,110.614697
2018-07-01 21:18:55,110.675,110.675,110.675,110.675,110.750,110.750,110.750,110.750,110.67500,110.75000,...,110.62360,110.634063,110.61826,110.622206,NaN,110.618286,NaN,110.616239,NaN,110.615637
2018-07-01 21:19:00,110.685,110.685,110.685,110.685,110.758,110.758,110.758,110.758,110.68500,110.75800,...,110.62745,110.638917,110.61998,110.624797,NaN,110.619986,NaN,110.617453,NaN,110.616705
2018-07-01 21:19:05,110.683,110.683,110.679,110.679,110.751,110.751,110.747,110.747,110.68100,110.74900,...,110.63050,110.642736,110.62192,110.627030,NaN,110.621482,NaN,110.618530,NaN,110.617654
2018-07-01 21:19:20,110.676,110.676,110.676,110.676,110.758,110.758,110.758,110.758,110.67600,110.75800,...,110.63440,110.645906,110.62356,110.629043,NaN,110.622856,NaN,110.619526,NaN,110.618532
2018-07-01 21:19:30,110.675,110.675,110.663,110.670,110.751,110.756,110.746,110.750,110.67075,110.75075,...,110.63830,110.648201,110.62504,110.630723,NaN,110.624038,NaN,110.620392,NaN,110.619299
2018-07-01 21:19:35,110.680,110.686,110.672,110.686,110.752,110.777,110.752,110.767,110.68100,110.76200,...,110.64290,110.651803,110.62656,110.632987,NaN,110.625583,NaN,110.621508,NaN,110.620282
2018-07-01 21:19:45,110.688,110.688,110.646,110.660,110.755,110.758,110.742,110.758,110.67050,110.75325,...,110.64585,110.652583,110.62750,110.634091,NaN,110.626437,NaN,110.622157,NaN,110.620861
2018-07-01 21:19:50,110.682,110.682,110.682,110.682,110.752,110.752,110.752,110.752,110.68200,110.75200,...,110.65020,110.655386,110.62878,110.636046,NaN,110.627809,NaN,110.623156,NaN,110.621742
2018-07-01 21:19:55,110.689,110.689,110.686,110.686,110.753,110.753,110.747,110.747,110.68750,110.75000,...,110.65425,110.658302,110.63044,110.638082,NaN,110.629238,NaN,110.624197,NaN,110.622660
2018-07-01 21:20:25,110.690,110.692,110.690,110.692,110.751,110.759,110.751,110.759,110.69100,110.75500,...,110.65815,110.661512,110.63156,110.640276,NaN,110.630773,NaN,110.625311,NaN,110.623640
2018-07-01 21:20:30,110.691,110.691,110.691,110.691,110.752,110.752,110.752,110.752,110.69100,110.75200,...,110.66205,110.664321,110.63262,110.642336,NaN,110.632239,NaN,110.626381,NaN,110.624582
2018-07-01 21:20:35,110.691,110.691,110.691,110.691,110.760,110.760,110.760,110.760,110.69100,110.76000,...,110.66580,110.666863,110.63380,110.644311,NaN,110.633662,NaN,110.627424,NaN,110.625502
2018-07-01 21:20:40,110.688,110.688,110.678,110.678,110.754,110.756,110.754,110.756,110.68300,110.75500,...,110.66840,110.667924,110.63480,110.645675,NaN,110.634732,NaN,110.628234,NaN,110.626222
2018-07-01 21:20:45,110.678,110.690,110.673,110.673,110.748,110.772,110.748,110.753,110.67850,110.75525,...,110.67105,110.668407,110.63578,110.646781,NaN,110.635651,NaN,110.628946,NaN,110.626857
2018-07-01 21:20:50,110.662,110.662,110.662,110.662,110.754,110.754,110.754,110.754,110.66200,110.75400,...,110.67305,110.667797,110.63650,110.647396,NaN,110.636281,NaN,110.629467,NaN,110.627330
2018-07-01 21:20:55,110.653,110.653,110.625,110.625,110.751,110.751,110.722,110.722,110.63900,110.73650,...,110.67205,110.663720,110.63630,110.646492,NaN,110.636013,NaN,110.629397,NaN,110.627299
2018-07-01 21:21:15,110.646,110.646,110.639,110.639,110.711,110.711,110.701,110.701,110.64250,110.70600,...,110.67230,110.661366,110.63654,110.646190,NaN,110.636083,NaN,110.629546,NaN,110.627453
2018-07-01 21:21:35,110.644,110.644,110.644,110.644,110.705,110.705,110.705,110.705,110.64400,110.70500,...,110.67230,110.659712,110.63740,110.646102,NaN,110.636270,NaN,110.629769,NaN,110.627670
2018-07-01 21:21:50,110.652,110.652,110.652,110.652,110.706,110.706,110.706,110.706,110.65200,110.70600,...,110.67135,110.658977,110.63828,110.646339,NaN,110.636641,NaN,110.630109,NaN,110.627985
2018-07-01 21:22:00,110.657,110.657,110.657,110.657,110.708,110.708,110.708,110.708,110.65700,110.70800,...,110.67015,110.658789,110.63912,110.646768,NaN,110.637118,NaN,110.630517,NaN,110.628358
2018-07-01 21:22:05,110.649,110.677,110.649,110.674,110.707,110.759,110.707,110.754,110.66225,110.73175,...,110.67010,110.660238,110.64010,110.647861,NaN,110.637980,NaN,110.631173,NaN,110.628940
2018-07-01 21:22:10,110.671,110.683,110.670,110.683,110.747,110.757,110.747,110.748,110.67675,110.74975,...,110.67000,110.662406,110.64108,110.649270,NaN,110.639028,NaN,110.631948,NaN,110.629622
2018-07-01 21:22:45,110.669,110.673,110.662,110.670,110.748,110.757,110.747,110.755,110.66850,110.75175,...,110.66955,110.663129,110.64172,110.650101,NaN,110.639747,NaN,110.632514,NaN,110.630128
2018-07-01 21:23:15,110.683,110.710,110.683,110.710,110.756,110.766,110.756,110.758,110.69650,110.75900,...,110.67125,110.667593,110.64322,110.652500,NaN,110.641372,NaN,110.633658,NaN,110.631119
2018-07-01 21:24:15,110.719,110.772,110.710,110.772,110.757,110.870,110.757,110.851,110.74325,110.80875,...,110.67635,110.677537,110.64674,110.657281,NaN,110.644382,NaN,110.635686,NaN,110.632853
2018-07-01 21:24:20,110.771,110.771,110.729,110.735,110.843,110.859,110.832,110.837,110.75150,110.84275,...,110.67880,110.683010,110.64930,110.660388,NaN,110.646464,NaN,110.637133,NaN,110.634100
2018-07-01 21:24:25,110.732,110.765,110.732,110.762,110.830,110.854,110.827,110.849,110.74775,110.84000,...,110.68390,110.690533,110.65236,110.664447,110.6325,110.649110,NaN,110.638940,NaN,110.635649

Index(['Bid_Open', 'Bid_High', 'Bid_Low', 'Bid_Close', 'Ask_Open', 'Ask_High',
       'Ask_Low', 'Ask_Close', 'BidAvg', 'AskAvg', 'Bid_SSMA5', 'Bid_SEMA5',
       'Bid_SSMA10', 'Bid_SEMA10', 'Bid_SSMA20', 'Bid_SEMA20', 'Bid_SSMA30',
       'Bid_SEMA30', 'Bid_SSMA40', 'Bid_SEMA40', 'Bid_SSMA50', 'Bid_SEMA50',
       'Bid_LSMA10', 'Bid_LEMA10', 'Bid_LSMA20', 'Bid_LEMA20', 'Bid_LSMA50',
       'Bid_LEMA50', 'Bid_LSMA100', 'Bid_LEMA100', 'Bid_LSMA250',
       'Bid_LEMA250', 'Bid_LSMA500', 'Bid_LEMA500'],
      dtype='object')

In [13]:
%matplotlib qt

#fig = plt.figure()
#ax1 = plt.subplot2grid((1,1), (0,0))

fig = plt.figure()
ax1 = fig.add_subplot(111) # in this function, first number 1 represent the height,
# second is for width and third is the plot number
ax2 = fig.add_subplot(111)

df_plot_sub['ohlc_date'] = df_plot_sub.index.map(mdates.date2num)

pre_ohlc = df_plot_sub[['ohlc_date','Bid_Open','Bid_High','Bid_Low','Bid_Close']]

ohlc = list(pre_ohlc.itertuples(index = False, name = None))

#need to set width to number of datapoints within a day (24*60*12)
candlestick_ohlc(ax1, ohlc, width=0.6/(24*60*12), colorup='#77d879', colordown='#db3f3f')

for label in ax1.xaxis.get_ticklabels():
    label.set_rotation(45)

ax1.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d %H:%M:%S'))
ax1.xaxis.set_major_locator(mticker.MaxNLocator(10))
ax1.grid(True)

df_plot_sub.MA10.plot(ax=ax2)
df_plot_sub.EMA10.plot(ax=ax2)

plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Test')
plt.legend()
plt.subplots_adjust(left=0.09, bottom=0.20, right=0.94, top=0.90, wspace=0.2, hspace=0)
plt.show()

C:\Users\pebaqu\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)
C:\Users\pebaqu\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [11]:
display(ohlc)

[(736876.875, 110.635, 110.635, 110.635, 110.635),
 (736876.8751736111, 110.584, 110.584, 110.584, 110.584),
 (736876.8755787037, 110.592, 110.592, 110.592, 110.592),
 (736876.8756365741, 110.588, 110.661, 110.588, 110.661),
 (736876.8756944444, 110.665, 110.665, 110.665, 110.665),
 (736876.8757523148, 110.66, 110.66, 110.596, 110.596),
 (736876.8758101852, 110.6, 110.6, 110.6, 110.6),
 (736876.8760416667, 110.604, 110.604, 110.604, 110.604),
 (736876.8762152778, 110.612, 110.622, 110.612, 110.622),
 (736876.8763888889, 110.622, 110.622, 110.622, 110.622),
 (736876.8764467592, 110.628, 110.628, 110.628, 110.628),
 (736876.8765046296, 110.624, 110.624, 110.602, 110.602),
 (736876.8767939815, 110.606, 110.606, 110.606, 110.606),
 (736876.8768518518, 110.61, 110.61, 110.61, 110.61),
 (736876.8769097222, 110.615, 110.615, 110.615, 110.615),
 (736876.8771412037, 110.61, 110.61, 110.61, 110.61),
 (736876.8773726852, 110.606, 110.606, 110.606, 110.606),
 (736876.8780092592, 110.601, 110.601, 110.601, 110.601),
 (736876.8782407407, 110.595, 110.595, 110.595, 110.595),
 (736876.8782986111, 110.588, 110.592, 110.582, 110.582),
 (736876.8784143518, 110.59, 110.59, 110.59, 110.59),
 (736876.8784722222, 110.593, 110.6, 110.593, 110.6),
 (736876.8787037038, 110.592, 110.6, 110.581, 110.589),
 (736876.878761574, 110.596, 110.597, 110.581, 110.588),
 (736876.8788194444, 110.595, 110.599, 110.59, 110.599),
 (736876.8792824075, 110.595, 110.595, 110.582, 110.582),
 (736876.8793402778, 110.594, 110.594, 110.594, 110.594),
 (736876.8799768519, 110.596, 110.596, 110.596, 110.596),
 (736876.880613426, 110.603, 110.61, 110.603, 110.61),
 (736876.8806712963, 110.613, 110.613, 110.613, 110.613),
 (736876.8811342593, 110.618, 110.618, 110.618, 110.618),
 (736876.8815393519, 110.613, 110.614, 110.603, 110.603),
 (736876.8815972222, 110.596, 110.636, 110.596, 110.636),
 (736876.8816550926, 110.631, 110.638, 110.631, 110.638),
 (736876.881712963, 110.644, 110.646, 110.629, 110.632),
 (736876.8817708333, 110.621, 110.631, 110.616, 110.628),
 (736876.8819444445, 110.628, 110.628, 110.622, 110.624),
 (736876.8821759259, 110.62, 110.626, 110.62, 110.626),
 (736876.882349537, 110.635, 110.635, 110.635, 110.635),
 (736876.8826967593, 110.627, 110.627, 110.627, 110.627),
 (736876.8835069444, 110.622, 110.626, 110.601, 110.601),
 (736876.8835648148, 110.608, 110.608, 110.608, 110.608),
 (736876.8836226852, 110.615, 110.615, 110.615, 110.615),
 (736876.8836805555, 110.618, 110.625, 110.618, 110.625),
 (736876.8837384259, 110.634, 110.634, 110.634, 110.634),
 (736876.8837962963, 110.639, 110.645, 110.638, 110.638),
 (736876.8838541667, 110.635, 110.635, 110.635, 110.635),
 (736876.8843171296, 110.624, 110.624, 110.594, 110.596),
 (736876.8846064815, 110.607, 110.607, 110.607, 110.607),
 (736876.8847222222, 110.603, 110.609, 110.598, 110.609),
 (736876.8847800926, 110.606, 110.606, 110.602, 110.602),
 (736876.8854166666, 110.602, 110.602, 110.602, 110.602),
 (736876.885474537, 110.6, 110.604, 110.6, 110.604),
 (736876.8855324074, 110.604, 110.604, 110.604, 110.604),
 (736876.8855902777, 110.608, 110.608, 110.608, 110.608),
 (736876.8857060185, 110.609, 110.618, 110.605, 110.618),
 (736876.8859953703, 110.601, 110.601, 110.597, 110.598),
 (736876.8860532407, 110.597, 110.597, 110.584, 110.592),
 (736876.8861111111, 110.598, 110.598, 110.59, 110.594),
 (736876.8862268518, 110.601, 110.601, 110.601, 110.601),
 (736876.8864583333, 110.608, 110.622, 110.588, 110.595),
 (736876.8865162038, 110.605, 110.605, 110.605, 110.605),
 (736876.886863426, 110.611, 110.614, 110.611, 110.614),
 (736876.8869791667, 110.609, 110.613, 110.555, 110.613),
 (736876.8870949075, 110.616, 110.616, 110.616, 110.616),
 (736876.8874421297, 110.622, 110.626, 110.622, 110.626),
 (736876.8875578704, 110.621, 110.621, 110.62, 110.62),
 (736876.8876157408, 110.622, 110.622, 110.622, 110.622),
 (736876.887673611, 110.62, 110.645, 110.608, 110.645),
 (736876.8877893519, 110.65, 110.65, 110.634, 110.634),
 (736876.8878472223, 110.644, 110.644, 110.644, 110.644),
 (736876.8879050926, 110.641, 110.671, 110.641, 110.671),
 (736876.8880208334, 110.702, 110.702, 110.681, 110.681),
 (736876.8881365741, 110.675, 110.675, 110.675, 110.675),
 (736876.8881944445, 110.685, 110.685, 110.685, 110.685),
 (736876.8882523148, 110.683, 110.683, 110.679, 110.679),
 (736876.888425926, 110.676, 110.676, 110.676, 110.676),
 (736876.8885416667, 110.675, 110.675, 110.663, 110.67),
 (736876.8885995371, 110.68, 110.686, 110.672, 110.686),
 (736876.8887152778, 110.688, 110.688, 110.646, 110.66),
 (736876.8887731482, 110.682, 110.682, 110.682, 110.682),
 (736876.8888310185, 110.689, 110.689, 110.686, 110.686),
 (736876.8891782408, 110.69, 110.692, 110.69, 110.692),
 (736876.8892361111, 110.691, 110.691, 110.691, 110.691),
 (736876.8892939815, 110.691, 110.691, 110.691, 110.691),
 (736876.8893518519, 110.688, 110.688, 110.678, 110.678),
 (736876.8894097222, 110.678, 110.69, 110.673, 110.673),
 (736876.8894675926, 110.662, 110.662, 110.662, 110.662),
 (736876.889525463, 110.653, 110.653, 110.625, 110.625),
 (736876.8897569445, 110.646, 110.646, 110.639, 110.639),
 (736876.8899884259, 110.644, 110.644, 110.644, 110.644),
 (736876.890162037, 110.652, 110.652, 110.652, 110.652),
 (736876.8902777778, 110.657, 110.657, 110.657, 110.657),
 (736876.8903356482, 110.649, 110.677, 110.649, 110.674),
 (736876.8903935185, 110.671, 110.683, 110.67, 110.683),
 (736876.8907986111, 110.669, 110.673, 110.662, 110.67),
 (736876.8911458333, 110.683, 110.71, 110.683, 110.71),
 (736876.8918402778, 110.719, 110.772, 110.71, 110.772),
 (736876.8918981481, 110.771, 110.771, 110.729, 110.735),
 (736876.8919560185, 110.732, 110.765, 110.732, 110.762)]

In [30]:
USD_JPY_df['Bid_Spread'] = USD_JPY_df['Bid_Open'] - USD_JPY_df['Bid_Close']
USD_JPY_df['Ask_Spread'] = USD_JPY_df['Ask_Open'] - USD_JPY_df['Ask_Close']
USD_JPY_df['Bid_Direction'] = 0
USD_JPY_df.loc[USD_JPY_df['Bid_Spread']>0,'Bid_Direction'] = 1
USD_JPY_df.loc[USD_JPY_df['Bid_Spread']<0,'Bid_Direction'] = -1
USD_JPY_df['rma'] = USD_JPY_df.groupby('Bid_Direction')['Bid_Direction'].transform(lambda x: x.mean())

In [31]:
display(USD_JPY_df)

,Complete,Volume,Time,Bid_Open,Bid_High,Bid_Low,Bid_Close,Ask_Open,Ask_High,Ask_Low,Ask_Close,Bid_Spread,Ask_Spread,Bid_Direction,Direction,rma
Time,,,,,,,,,,,,,,,,
2018-07-01 21:00:00,b'True',1,2018-07-01 21:00:00,110.635,110.635,110.635,110.635,110.715,110.715,110.715,110.715,0.000,0.000,0,NaN,0
2018-07-01 21:00:15,b'True',1,2018-07-01 21:00:15,110.584,110.584,110.584,110.584,110.664,110.664,110.664,110.664,0.000,0.000,0,NaN,0
2018-07-01 21:00:50,b'True',1,2018-07-01 21:00:50,110.592,110.592,110.592,110.592,110.672,110.672,110.672,110.672,0.000,0.000,0,NaN,0
2018-07-01 21:00:55,b'True',4,2018-07-01 21:00:55,110.588,110.661,110.588,110.661,110.668,110.741,110.668,110.741,-0.073,-0.073,-1,Down,-1
2018-07-01 21:01:00,b'True',1,2018-07-01 21:01:00,110.665,110.665,110.665,110.665,110.745,110.745,110.745,110.745,0.000,0.000,0,NaN,0
2018-07-01 21:01:05,b'True',5,2018-07-01 21:01:05,110.660,110.660,110.596,110.596,110.740,110.740,110.676,110.676,0.064,0.064,1,Up,1
2018-07-01 21:01:10,b'True',1,2018-07-01 21:01:10,110.600,110.600,110.600,110.600,110.680,110.680,110.680,110.680,0.000,0.000,0,NaN,0
2018-07-01 21:01:30,b'True',1,2018-07-01 21:01:30,110.604,110.604,110.604,110.604,110.684,110.684,110.684,110.684,0.000,0.000,0,NaN,0
2018-07-01 21:01:45,b'True',3,2018-07-01 21:01:45,110.612,110.622,110.612,110.622,110.692,110.702,110.692,110.702,-0.010,-0.010,-1,Down,-1
2018-07-01 21:02:00,b'True',2,2018-07-01 21:02:00,110.622,110.622,110.622,110.622,110.702,110.702,110.702,110.702,0.000,0.000,0,NaN,0
2018-07-01 21:02:05,b'True',1,2018-07-01 21:02:05,110.628,110.628,110.628,110.628,110.708,110.708,110.708,110.708,0.000,0.000,0,NaN,0
2018-07-01 21:02:10,b'True',5,2018-07-01 21:02:10,110.624,110.624,110.602,110.602,110.702,110.702,110.682,110.682,0.022,0.020,1,Up,1
2018-07-01 21:02:35,b'True',1,2018-07-01 21:02:35,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686,0.000,0.000,0,NaN,0
2018-07-01 21:02:40,b'True',1,2018-07-01 21:02:40,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690,0.000,0.000,0,NaN,0
2018-07-01 21:02:45,b'True',1,2018-07-01 21:02:45,110.615,110.615,110.615,110.615,110.695,110.695,110.695,110.695,0.000,0.000,0,NaN,0
2018-07-01 21:03:05,b'True',1,2018-07-01 21:03:05,110.610,110.610,110.610,110.610,110.690,110.690,110.690,110.690,0.000,0.000,0,NaN,0
2018-07-01 21:03:25,b'True',1,2018-07-01 21:03:25,110.606,110.606,110.606,110.606,110.686,110.686,110.686,110.686,0.000,0.000,0,NaN,0
2018-07-01 21:04:20,b'True',1,2018-07-01 21:04:20,110.601,110.601,110.601,110.601,110.681,110.681,110.681,110.681,0.000,0.000,0,NaN,0
2018-07-01 21:04:40,b'True',1,2018-07-01 21:04:40,110.595,110.595,110.595,110.595,110.675,110.675,110.675,110.675,0.000,0.000,0,NaN,0
2018-07-01 21:04:45,b'True',4,2018-07-01 21:04:45,110.588,110.592,110.582,110.582,110.668,110.672,110.662,110.662,0.006,0.006,1,Up,1
2018-07-01 21:04:55,b'True',1,2018-07-01 21:04:55,110.590,110.590,110.590,110.590,110.667,110.667,110.667,110.667,0.000,0.000,0,NaN,0
2018-07-01 21:05:00,b'True',2,2018-07-01 21:05:00,110.593,110.600,110.593,110.600,110.673,110.680,110.673,110.680,-0.007,-0.007,-1,Down,-1
2018-07-01 21:05:20,b'True',30,2018-07-01 21:05:20,110.592,110.600,110.581,110.589,110.672,110.680,110.661,110.669,0.003,0.003,1,Up,1
2018-07-01 21:05:25,b'True',22,2018-07-01 21:05:25,110.596,110.597,110.581,110.588,110.676,110.677,110.661,110.668,0.008,0.008,1,Up,1
2018-07-01 21:05:30,b'True',6,2018-07-01 21:05:30,110.595,110.599,110.590,110.599,110.675,110.679,110.670,110.679,-0.004,-0.004,-1,Down,-1
2018-07-01 21:06:10,b'True',3,2018-07-01 21:06:10,110.595,110.595,110.582,110.582,110.675,110.675,110.662,110.662,0.013,0.013,1,Up,1
2018-07-01 21:06:15,b'True',1,2018-07-01 21:06:15,110.594,110.594,110.594,110.594,110.658,110.658,110.658,110.658,0.000,0.000,0,NaN,0
2018-07-01 21:07:10,b'True',1,2018-07-01 21:07:10,110.596,110.596,110.596,110.596,110.665,110.665,110.665,110.665,0.000,0.000,0,NaN,0
2018-07-01 21:08:05,b'True',2,2018-07-01 21:08:05,110.603,110.610,110.603,110.610,110.668,110.669,110.668,110.669,-0.007,-0.001,-1,Down,-1
2018-07-01 21:08:10,b'True',1,2018-07-01 21:08:10,110.613,110.613,110.613,110.613,110.675,110.675,110.675,110.675,0.000,0.000,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-31 23:56:45,b'True',3,2018-07-31 23:56:45,111.774,111.778,111.774,111.778,111.788,111.793,111.788,111.793,-0.004,-0.005,-1,Down,-1
2018-07-31 23:57:00,b'True',4,2018-07-31 23:57:00,111.776,111.778,111.774,111.774,111.791,111.793,111.788,111.788,0.002,0.003,1,Up,1
2018-07-31 23:57:05,b'True',5,2018-07-31 23:57:05,111.776,111.786,111.776,111.786,111.791,111.800,111.791,111.800,-0.010,-0.009,-1,Down,-1
2018-07-31 23:57:10,b'True',2,2018-07-31 23:57:10,111.788,111.790,111.788,111.790,111.803,111.805,111.803,111.805,-0.002,-0.002,-1,Down,-1
2018-07-31 23:57:15,b'True',4,2018-07-31 23:57:15,111.788,111.788,111.781,111.781,111.803,111.803,111.796,111.796,0.007,0.007,1,Up,1
2018-07-31 23:57:20,b'True',2,2018-07-31 23:57:20,111.784,111.784,111.781,111.781,111.797,111.797,111.796,111.796,0.003,0.001,1,Up,1
2018-07-31 23:57:25,b'True',3,2018-07-31 23:57:25,111.784,111.788,111.784,111.788,111.797,111.803,111.797,111.803,-0.004,-0.006,-1,Down,-1
2018-07-31 23:57:35,b'True',4,2018-07-31 23:57:35,111.790,111.790,111.786,111.789,111.805,111.805,111.801,111.803,0.001,0.002,1,Up,1
2018-07-31 23:57:40,b'True',2,2018-07-31 23:57:40,111.791,111.794,111.791,111.794,111.806,111.807,111.806,111.807,-0.003,-0.001,-1,Down,-1
2018-07-31 23:57:45,b'True',3,2018-07-31 23:57:45,111.796,111.796,111.791,111.791,111.810,111.810,111.805,111.805,0.005,0.005,1,Up,1
2018-07-31 23:57:50,b'True',2,2018-07-31 23:57:50,111.793,111.793,111.791,111.791,111.807,111.807,111.805,111.805,0.002,0.002,1,Up,1
2018-07-31 23:57:55,b'True',1,2018-07-31 23:57:55,111.792,111.792,111.792,111.792,111.808,111.808,111.808,111.808,0.000,0.000,0,NaN,0
2018-07-31 23:58:00,b'True',1,2018-07-31 23:58:00,111.796,111.796,111.796,111.796,111.809,111.809,111.809,111.809,0.000,0.000,0,NaN,0
2018-07-31 23:58:20,b'True',5,2018-07-31 23:58:20,111.798,111.808,111.798,111.808,111.812,111.821,111.812,111.821,-0.010,-0.009,-1,Down,-1
2018-07-31 23:58:25,b'True',7,2018-07-31 23:58:25,111.810,111.815,111.806,111.806,111.824,111.829,111.820,111.820,0.004,0.004,1,Up,1
2018-07-31 23:58:30,b'True',1,2018-07-31 23:58:30,111.803,111.803,111.803,111.803,111.818,111.818,111.818,111.818,0.000,0.000,0,NaN,0
2018-07-31 23:58:35,b'True',1,2018-07-31 23:58:35,111.800,111.800,111.800,111.800,111.815,111.815,111.815,111.815,0.000,0.000,0,NaN,0
2018-07-31 23:58:40,b'True',1,2018-07-31 23:58:40,111.803,111.803,111.803,111.803,111.817,111.817,111.817,111.817,0.000,0.000,0,NaN,0
2018-07-31 23:58:45,b'True',1,2018-07-31 23:58:45,111.805,111.805,111.805,111.805,111.819,111.819,111.819,111.819,0.000,0.000,0,NaN,0
2018-07-31 23:58:50,b'True',5,2018-07-31 23:58:50,111.803,111.803,111.800,111.803,111.817,111.818,111.814,111.818,0.000,-0.001,0,NaN,0
2018-07-31 23:58:55,b'True',1,2018-07-31 23:58:55,111.806,111.806,111.806,111.806,111.819,111.819,111.819,111.819,0.000,0.000,0,NaN,0
2018-07-31 23:59:00,b'True',2,2018-07-31 23:59:00,111.807,111.809,111.807,111.809,111.822,111.825,111.822,111.825,-0.002,-0.003,-1,Down,-1
2018-07-31 23:59:05,b'True',3,2018-07-31 23:59:05,111.812,111.817,111.812,111.817,111.827,111.832,111.827,111.832,-0.005,-0.005,-1,Down,-1
2018-07-31 23:59:10,b'True',4,2018-07-31 23:59:10,111.819,111.819,111.817,111.817,111.834,111.834,111.831,111.831,0.002,0.003,1,Up,1
2018-07-31 23:59:30,b'True',1,2018-07-31 23:59:30,111.814,111.814,111.814,111.814,111.828,111.828,111.828,111.828,0.000,0.000,0,NaN,0
2018-07-31 23:59:40,b'True',6,2018-07-31 23:59:40,111.812,111.818,111.808,111.818,111.826,111.833,111.824,111.833,-0.006,-0.007,-1,Down,-1
2018-07-31 23:59:45,b'True',2,2018-07-31 23:59:45,111.821,111.821,111.819,111.819,111.835,111.835,111.832,111.832,0.002,0.003,1,Up,1
2018-07-31 23:59:50,b'True',4,2018-07-31 23:59:50,111.821,111.828,111.821,111.828,111.835,111.842,111.835,111.842,-0.007,-0.007,-1,Down,-1
2018-07-31 23:59:55,b'True',4,2018-07-31 23:59:55,111.826,111.828,111.826,111.828,111.839,111.843,111.839,111.843,-0.002,-0.004,-1,Down,-1
2018-08-01 00:00:00,b'True',16,2018-08-01 00:00:00,111.826,111.826,111.794,111.799,111.841,111.841,111.809,111.814,0.027,0.027,1,Up,1